<Project Sdk="Microsoft.NET.Sdk.Web">
    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Npgsql.OpenTelemetry"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime"/>
        <PackageReference Include="Scrutor"/>
    </ItemGroup>

    <!-- Exclude client app from build -->
    <ItemGroup>
        <Content Remove="../react-client/**"/>
        <Compile Remove="../react-client/**"/>
        <EmbeddedResource Remove="../react-client/**"/>
        <None Remove="../react-client/**"/>
    </ItemGroup>

    <!-- Build React app during publish -->
    <Target Name="BuildClientApp" BeforeTargets="Build" Condition="'$(Configuration)'=='Release'">
        <Message Text="Building React app..." Importance="high"/>
        <Exec Command="npm ci" WorkingDirectory="../react-client"/>
        <Exec Command="npm run build" WorkingDirectory="../react-client"/>
    </Target>

    <!-- Include built client files -->
    <ItemGroup Condition="'$(Configuration)'=='Release'">
        <Content Include="../react-client/dist/**/*.*" LinkBase="wwwroot/" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

</Project>
