// <auto-generated />
using System;
using GainFlow.Api.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GainFlow.Api.Infrastructure.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250822112324_Add_WorkoutPrograms")]
    partial class Add_WorkoutPrograms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_exercises_name");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ExerciseMuscleGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercise_muscle_group");

                    b.HasIndex("ExerciseId", "MuscleGroup", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_muscle_group_exercise_id_muscle_group_role");

                    b.ToTable("exercise_muscle_group", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramDay", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_number");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ProgramWeekId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("program_week_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_program_days");

                    b.HasIndex("ProgramWeekId", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_program_days_program_week_id_day_number");

                    b.ToTable("program_days", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramExercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index");

                    b.Property<string>("ProgramSetGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("program_set_group_id");

                    b.Property<string>("ProgressionRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("progression_rule");

                    b.Property<string>("TargetReps")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_reps");

                    b.Property<string>("TargetRpe")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_rpe");

                    b.Property<int>("TargetSets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_sets");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_weight");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_program_exercises");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_program_exercises_exercise_id");

                    b.HasIndex("ProgramSetGroupId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_program_exercises_program_set_group_id_order_index");

                    b.ToTable("program_exercises", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramSetGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index");

                    b.Property<string>("ProgramDayId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("program_day_id");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rest_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_program_set_groups");

                    b.HasIndex("ProgramDayId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_program_set_groups_program_day_id_order_index");

                    b.ToTable("program_set_groups", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramWeek", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("week_number");

                    b.Property<string>("WorkoutProgramId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workout_program_id");

                    b.HasKey("Id")
                        .HasName("pk_program_weeks");

                    b.HasIndex("WorkoutProgramId", "WeekNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_program_weeks_workout_program_id_week_number");

                    b.ToTable("program_weeks", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<float?>("Height")
                        .HasColumnType("REAL")
                        .HasColumnName("height");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<float?>("Weight")
                        .HasColumnType("REAL")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.UserProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_day");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_week");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkoutProgramId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workout_program_id");

                    b.HasKey("Id")
                        .HasName("pk_user_programs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_programs_user_id");

                    b.HasIndex("WorkoutProgramId")
                        .HasDatabaseName("ix_user_programs_workout_program_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_user_programs_user_id_status");

                    b.ToTable("user_programs", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutProgram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_weeks");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workout_programs");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_workout_programs_created_by_user_id");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("ix_workout_programs_is_public");

                    b.ToTable("workout_programs", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_number");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_completed");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ProgramDayId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("program_day_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserProgramId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_program_id");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("week_number");

                    b.Property<DateOnly>("WorkoutDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("workout_date");

                    b.HasKey("Id")
                        .HasName("pk_workout_sessions");

                    b.HasIndex("ProgramDayId")
                        .HasDatabaseName("ix_workout_sessions_program_day_id");

                    b.HasIndex("UserProgramId", "WorkoutDate")
                        .HasDatabaseName("ix_workout_sessions_user_program_id_workout_date");

                    b.HasIndex("UserProgramId", "WeekNumber", "DayNumber")
                        .HasDatabaseName("ix_workout_sessions_user_program_id_week_number_day_number");

                    b.ToTable("workout_sessions", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutSet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<bool>("IsWarmup")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_warmup");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("ProgramExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("program_exercise_id");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reps");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rest_seconds");

                    b.Property<int?>("Rpe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rpe");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("set_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("weight");

                    b.Property<string>("WorkoutSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_sets");

                    b.HasIndex("ProgramExerciseId")
                        .HasDatabaseName("ix_workout_sets_program_exercise_id");

                    b.HasIndex("ExerciseId", "WorkoutSessionId")
                        .HasDatabaseName("ix_workout_sets_exercise_id_workout_session_id");

                    b.HasIndex("WorkoutSessionId", "ProgramExerciseId", "SetNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workout_sets_workout_session_id_program_exercise_id_set_number");

                    b.ToTable("workout_sets", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSet_Rpe", "Rpe BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.Exercise", "Exercise")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_muscle_group_exercises_exercise_id");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramDay", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.ProgramWeek", "ProgramWeek")
                        .WithMany("Days")
                        .HasForeignKey("ProgramWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_days_program_weeks_program_week_id");

                    b.Navigation("ProgramWeek");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramExercise", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_exercises_exercises_exercise_id");

                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.ProgramSetGroup", "ProgramSetGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("ProgramSetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_exercises_program_set_groups_program_set_group_id");

                    b.Navigation("Exercise");

                    b.Navigation("ProgramSetGroup");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramSetGroup", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.ProgramDay", "ProgramDay")
                        .WithMany("SetGroups")
                        .HasForeignKey("ProgramDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_set_groups_program_days_program_day_id");

                    b.Navigation("ProgramDay");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramWeek", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.WorkoutProgram", "WorkoutProgram")
                        .WithMany("Weeks")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_weeks_workout_programs_workout_program_id");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.UserProgram", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_programs_users_user_id");

                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.WorkoutProgram", "WorkoutProgram")
                        .WithMany("UserPrograms")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_programs_workout_programs_workout_program_id");

                    b.Navigation("User");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutProgram", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_programs_users_created_by_user_id");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.ProgramDay", "ProgramDay")
                        .WithMany()
                        .HasForeignKey("ProgramDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sessions_program_days_program_day_id");

                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.UserProgram", "UserProgram")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sessions_user_programs_user_program_id");

                    b.Navigation("ProgramDay");

                    b.Navigation("UserProgram");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutSet", b =>
                {
                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sets_exercises_exercise_id");

                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.ProgramExercise", "ProgramExercise")
                        .WithMany()
                        .HasForeignKey("ProgramExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sets_program_exercises_program_exercise_id");

                    b.HasOne("GainFlow.Api.Shared.Domain.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_sets_workout_sessions_workout_session_id");

                    b.Navigation("Exercise");

                    b.Navigation("ProgramExercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("MuscleGroups");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramDay", b =>
                {
                    b.Navigation("SetGroups");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramSetGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.ProgramWeek", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.UserProgram", b =>
                {
                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutProgram", b =>
                {
                    b.Navigation("UserPrograms");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("GainFlow.Api.Shared.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
