// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GainFlow.Api.Infrastructure.Data.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_WorkoutPrograms : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "workout_programs",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: false),
                    created_by_user_id = table.Column<string>(type: "TEXT", nullable: false),
                    duration_weeks = table.Column<int>(type: "INTEGER", nullable: false),
                    is_public = table.Column<bool>(type: "INTEGER", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_workout_programs", x => x.id);
                    table.ForeignKey(
                        name: "fk_workout_programs_users_created_by_user_id",
                        column: x => x.created_by_user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "program_weeks",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    workout_program_id = table.Column<string>(type: "TEXT", nullable: false),
                    week_number = table.Column<int>(type: "INTEGER", nullable: false),
                    name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_program_weeks", x => x.id);
                    table.ForeignKey(
                        name: "fk_program_weeks_workout_programs_workout_program_id",
                        column: x => x.workout_program_id,
                        principalTable: "workout_programs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "user_programs",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    user_id = table.Column<string>(type: "TEXT", nullable: false),
                    workout_program_id = table.Column<string>(type: "TEXT", nullable: false),
                    start_date = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    end_date = table.Column<DateOnly>(type: "TEXT", nullable: true),
                    status = table.Column<string>(type: "TEXT", nullable: false),
                    current_week = table.Column<int>(type: "INTEGER", nullable: false),
                    current_day = table.Column<int>(type: "INTEGER", nullable: false),
                    notes = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_user_programs", x => x.id);
                    table.ForeignKey(
                        name: "fk_user_programs_users_user_id",
                        column: x => x.user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_user_programs_workout_programs_workout_program_id",
                        column: x => x.workout_program_id,
                        principalTable: "workout_programs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "program_days",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    program_week_id = table.Column<string>(type: "TEXT", nullable: false),
                    day_number = table.Column<int>(type: "INTEGER", nullable: false),
                    name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    description = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_program_days", x => x.id);
                    table.ForeignKey(
                        name: "fk_program_days_program_weeks_program_week_id",
                        column: x => x.program_week_id,
                        principalTable: "program_weeks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "program_set_groups",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    program_day_id = table.Column<string>(type: "TEXT", nullable: false),
                    order_index = table.Column<int>(type: "INTEGER", nullable: false),
                    type = table.Column<string>(type: "TEXT", nullable: false),
                    rest_seconds = table.Column<int>(type: "INTEGER", nullable: false),
                    notes = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_program_set_groups", x => x.id);
                    table.ForeignKey(
                        name: "fk_program_set_groups_program_days_program_day_id",
                        column: x => x.program_day_id,
                        principalTable: "program_days",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "workout_sessions",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    user_program_id = table.Column<string>(type: "TEXT", nullable: false),
                    program_day_id = table.Column<string>(type: "TEXT", nullable: false),
                    workout_date = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    start_time = table.Column<TimeOnly>(type: "TEXT", nullable: true),
                    end_time = table.Column<TimeOnly>(type: "TEXT", nullable: true),
                    week_number = table.Column<int>(type: "INTEGER", nullable: false),
                    day_number = table.Column<int>(type: "INTEGER", nullable: false),
                    notes = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: true),
                    is_completed = table.Column<bool>(type: "INTEGER", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_workout_sessions", x => x.id);
                    table.ForeignKey(
                        name: "fk_workout_sessions_program_days_program_day_id",
                        column: x => x.program_day_id,
                        principalTable: "program_days",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_workout_sessions_user_programs_user_program_id",
                        column: x => x.user_program_id,
                        principalTable: "user_programs",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "program_exercises",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    program_set_group_id = table.Column<string>(type: "TEXT", nullable: false),
                    exercise_id = table.Column<string>(type: "TEXT", nullable: false),
                    order_index = table.Column<int>(type: "INTEGER", nullable: false),
                    target_sets = table.Column<int>(type: "INTEGER", nullable: false),
                    target_reps = table.Column<string>(type: "TEXT", maxLength: 50, nullable: false),
                    target_weight = table.Column<decimal>(type: "TEXT", precision: 10, scale: 2, nullable: true),
                    target_rpe = table.Column<string>(type: "TEXT", maxLength: 20, nullable: true),
                    notes = table.Column<string>(type: "TEXT", maxLength: 1000, nullable: true),
                    progression_rule = table.Column<string>(type: "TEXT", maxLength: 500, nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_program_exercises", x => x.id);
                    table.ForeignKey(
                        name: "fk_program_exercises_exercises_exercise_id",
                        column: x => x.exercise_id,
                        principalTable: "exercises",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_program_exercises_program_set_groups_program_set_group_id",
                        column: x => x.program_set_group_id,
                        principalTable: "program_set_groups",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "workout_sets",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    workout_session_id = table.Column<string>(type: "TEXT", nullable: false),
                    program_exercise_id = table.Column<string>(type: "TEXT", nullable: false),
                    exercise_id = table.Column<string>(type: "TEXT", nullable: false),
                    set_number = table.Column<int>(type: "INTEGER", nullable: false),
                    reps = table.Column<int>(type: "INTEGER", nullable: false),
                    weight = table.Column<decimal>(type: "TEXT", precision: 10, scale: 2, nullable: false),
                    rpe = table.Column<int>(type: "INTEGER", nullable: true),
                    rest_seconds = table.Column<int>(type: "INTEGER", nullable: true),
                    notes = table.Column<string>(type: "TEXT", maxLength: 500, nullable: true),
                    is_warmup = table.Column<bool>(type: "INTEGER", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_workout_sets", x => x.id);
                    table.CheckConstraint("CK_WorkoutSet_Rpe", "Rpe BETWEEN 1 AND 10");
                    table.ForeignKey(
                        name: "fk_workout_sets_exercises_exercise_id",
                        column: x => x.exercise_id,
                        principalTable: "exercises",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_workout_sets_program_exercises_program_exercise_id",
                        column: x => x.program_exercise_id,
                        principalTable: "program_exercises",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_workout_sets_workout_sessions_workout_session_id",
                        column: x => x.workout_session_id,
                        principalTable: "workout_sessions",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_program_days_program_week_id_day_number",
                table: "program_days",
                columns: new[] { "program_week_id", "day_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_program_exercises_exercise_id",
                table: "program_exercises",
                column: "exercise_id");

            migrationBuilder.CreateIndex(
                name: "ix_program_exercises_program_set_group_id_order_index",
                table: "program_exercises",
                columns: new[] { "program_set_group_id", "order_index" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_program_set_groups_program_day_id_order_index",
                table: "program_set_groups",
                columns: new[] { "program_day_id", "order_index" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_program_weeks_workout_program_id_week_number",
                table: "program_weeks",
                columns: new[] { "workout_program_id", "week_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_user_programs_user_id",
                table: "user_programs",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_user_programs_user_id_status",
                table: "user_programs",
                columns: new[] { "user_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_user_programs_workout_program_id",
                table: "user_programs",
                column: "workout_program_id");

            migrationBuilder.CreateIndex(
                name: "ix_workout_programs_created_by_user_id",
                table: "workout_programs",
                column: "created_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_workout_programs_is_public",
                table: "workout_programs",
                column: "is_public");

            migrationBuilder.CreateIndex(
                name: "ix_workout_sessions_program_day_id",
                table: "workout_sessions",
                column: "program_day_id");

            migrationBuilder.CreateIndex(
                name: "ix_workout_sessions_user_program_id_week_number_day_number",
                table: "workout_sessions",
                columns: new[] { "user_program_id", "week_number", "day_number" });

            migrationBuilder.CreateIndex(
                name: "ix_workout_sessions_user_program_id_workout_date",
                table: "workout_sessions",
                columns: new[] { "user_program_id", "workout_date" });

            migrationBuilder.CreateIndex(
                name: "ix_workout_sets_exercise_id_workout_session_id",
                table: "workout_sets",
                columns: new[] { "exercise_id", "workout_session_id" });

            migrationBuilder.CreateIndex(
                name: "ix_workout_sets_program_exercise_id",
                table: "workout_sets",
                column: "program_exercise_id");

            migrationBuilder.CreateIndex(
                name: "ix_workout_sets_workout_session_id_program_exercise_id_set_number",
                table: "workout_sets",
                columns: new[] { "workout_session_id", "program_exercise_id", "set_number" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "workout_sets");

            migrationBuilder.DropTable(
                name: "program_exercises");

            migrationBuilder.DropTable(
                name: "workout_sessions");

            migrationBuilder.DropTable(
                name: "program_set_groups");

            migrationBuilder.DropTable(
                name: "user_programs");

            migrationBuilder.DropTable(
                name: "program_days");

            migrationBuilder.DropTable(
                name: "program_weeks");

            migrationBuilder.DropTable(
                name: "workout_programs");
        }
    }
}
