// <auto-generated />
using System;
using GainFlow.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GainFlow.Api.Infrastructure.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720175136_Add_Exercise")]
    partial class Add_Exercise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GainFlow.Api.Infrastructure.Data.Entities.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_exercises_name");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Infrastructure.Data.Entities.ExerciseMuscleGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exercise_id");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("muscle_group");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercise_muscle_group");

                    b.HasIndex("ExerciseId", "MuscleGroup", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_muscle_group_exercise_id_muscle_group_role");

                    b.ToTable("exercise_muscle_group", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Infrastructure.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<float?>("Height")
                        .HasColumnType("REAL")
                        .HasColumnName("height");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<float?>("Weight")
                        .HasColumnType("REAL")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GainFlow.Api.Infrastructure.Data.Entities.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("GainFlow.Api.Infrastructure.Data.Entities.Exercise", "Exercise")
                        .WithMany("MuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_muscle_group_exercises_exercise_id");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("GainFlow.Api.Infrastructure.Data.Entities.Exercise", b =>
                {
                    b.Navigation("MuscleGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
