// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GainFlow.Api.Infrastructure.Data.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Exercise : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "exercises",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    name = table.Column<string>(type: "TEXT", maxLength: 200, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_exercises", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "exercise_muscle_group",
                columns: table => new
                {
                    id = table.Column<string>(type: "TEXT", nullable: false),
                    exercise_id = table.Column<string>(type: "TEXT", nullable: false),
                    muscle_group = table.Column<string>(type: "TEXT", nullable: false),
                    role = table.Column<string>(type: "TEXT", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_exercise_muscle_group", x => x.id);
                    table.ForeignKey(
                        name: "fk_exercise_muscle_group_exercises_exercise_id",
                        column: x => x.exercise_id,
                        principalTable: "exercises",
                        principalColumn: "id");
                });

            migrationBuilder.CreateIndex(
                name: "ix_exercise_muscle_group_exercise_id_muscle_group_role",
                table: "exercise_muscle_group",
                columns: new[] { "exercise_id", "muscle_group", "role" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_exercises_name",
                table: "exercises",
                column: "name",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "exercise_muscle_group");

            migrationBuilder.DropTable(
                name: "exercises");
        }
    }
}
